### ISSUE TITLE
Ezitis Migla

### ISSUE THREAD

**Issue by gibson** [beerjs/riga#2]
26 August 2020, Wednesday

[Ezitis Migla](http://ezitis.lv/en/)
[Avotu street 32a](http://ezitis.lv/en/avotu-ezitis-migla/)

7:00 p.m.

If you'll come let us know by commenting this issue

**Comment by limiterCore** [comment]
+1

**Comment by gibson** [comment]
Well, that was 2 people.
[no photo] today without a photo.

Discussed:
* Typescript 4
* GraphQL
* Nest.JS
* Rigas architecture
