### ISSUE TITLE
23 September  2020 - BEERA Bar Riga

### ISSUE THREAD

**Issue by gibson** [beerjs/riga#4]
23 September 2020, Wednesday

[BEERA Bar Riga](https://www.facebook.com/beerariga/)
[BEERA Bar, Ģertrūdes iela 39-31, Centra rajons, Rīga, LV-1011](https://www.google.com/maps/place/BEERA+Bar/@56.9541409,24.1267139,17z/data=!3m1!4b1!4m5!3m4!1s0x46eecf49047f8177:0x90caca058cf74a4c!8m2!3d56.9541409!4d24.1289026)

[Link to ics file](https://drive.google.com/file/d/1n2A6d6YM2rWwCbkrnDSZx8AfnqeRT--n/view?usp=sharing)

7:00 p.m.

If you'll come let us know by commenting on this issue

**Comment by VadimIpatov** [comment]
want to come, but I'm a golang developer, not js :) it's permitted?

**Comment by VadimIpatov** [comment]
want to come, but I'm a golang developer, not js :) it's permitted?

**Comment by gibson** [comment]
Of course, we not any restrictions.

**Comment by gibson** [comment]
> want to come, but I'm a golang developer, not js :) it's permitted?

Of course, we don't have any restriction

**Comment by evo-home-task** [comment]
🐨

**Comment by Ahelios** [comment]
Would gladly join but need to finish moving out of my old flat. :(

**Comment by limiterCore** [comment]
🐨

**Comment by gibson** [comment]
Well, that was 5 people.
![20200923_230218](https://user-images.githubusercontent.com/140022/94124515-c6444d00-fe5d-11ea-888c-b3e77c148ec1.jpg)


Discussed:
Films and series
Table games
Mortgage
Gambling
